### ISSUE TITLE
Pods’ Swift 2.3 version

### ISSUE THREAD

**Issue by oferRounds** [BeauNouvelle/FaceAware#16]
Hi,

First of all — cool library, thanks for sharing it!

I’d like to use the Swift 2.3 version, what version should I refer to on my cocoa pods?

Thanks!

**Comment by BeauNouvelle** [comment]
Unfortunately pods support was added after FaceAware had been updated to Swift 3.0.

There was a short time early on where the project supported both but that was only during that rough time period of transition.

You can try this [commit](https://github.com/BeauNouvelle/FaceAware/tree/7a2f8cff4ddc508d4b8bf3b64aa2913daa8b243a), it's an early version so I can't tell you how stable it will be. Many improvements since then, and of course no cocoapods support.

**Comment by oferRounds** [comment]
@BeauNouvelle — Thanks! I’ll check it out.

**Comment by oferRounds** [comment]
@BeauNouvelle — I’ve created a fork, and downgraded the code to use Swift 2.3. My question: I sometimes get the following error: `CreateWrappedSurface() failed for a dataprovider-backed CGImageRef.`. 
Looking on Stack OverFlow, the suggestions I tried did not solve it. Any idea?

**Comment by BeauNouvelle** [comment]
Try compare it to that commit I linked. I can't really help you out much further as I don't have an older version of Xcode that supports swift 2.3

**Comment by oferRounds** [comment]
👍
